/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package formulario;

import PatronesComportamiento.Iterador;
import PatronesComportamiento.IteratorProductos;
import PatronesComportamiento.Memento.EstadoFormulario;
import PatronesComportamiento.Memento.FormularioVenta;
import PatronesComportamiento.Responsabilidad;
import PatronesComportamiento.Strategy.*;
import PatronesEstructurales.FacadeAlquiler;
import PatronesCreacionales.ComprobanteBuilder;
import controlador.ControlAlquiler;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Michel Mendez
 */
public class alquiler extends javax.swing.JPanel {

    private EstadoFormulario mementoFormulario;
    //private PatronesComportamiento.Memento.EstadoFormulario mementoFormulario;

    /**
     * Creates new form alquiler
     */
    public alquiler() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtbuscarcliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbclientes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnMostrarClientesIterator = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSidcliente = new javax.swing.JTextField();
        txtSnombrecliente = new javax.swing.JTextField();
        txtSappaterno = new javax.swing.JTextField();
        txtSapmaterno = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtSidproducto = new javax.swing.JTextField();
        txtSnombreproducto = new javax.swing.JTextField();
        txtSprecioproducto = new javax.swing.JTextField();
        txtSstockproducto = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtSprecioventa = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtcantidadventa = new javax.swing.JTextField();
        btnagregarproducto = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtbuscarproductos = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbproductos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnMostrarProductosIterator = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btneliminarresumenventa = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbresumenventa = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btncobrar = new javax.swing.JButton();
        lbliva = new javax.swing.JLabel();
        lbltotal = new javax.swing.JLabel();
        lblUltimaFactura = new javax.swing.JLabel();
        cmbDescuento = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        btnAplicarDescuento = new javax.swing.JButton();
        btnRestaurarFormulario = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clientes Disponibles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Buscador:");

        txtbuscarcliente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtbuscarcliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarclienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscarclienteKeyTyped(evt);
            }
        });

        tbclientes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tbclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbclientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbclientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbclientes);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Click para  Seleccionar");

        btnMostrarClientesIterator.setBackground(new java.awt.Color(255, 255, 51));
        btnMostrarClientesIterator.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnMostrarClientesIterator.setForeground(new java.awt.Color(0, 0, 0));
        btnMostrarClientesIterator.setText("Mostrar Clientes");
        btnMostrarClientesIterator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarClientesIteratorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtbuscarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMostrarClientesIterator))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtbuscarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnMostrarClientesIterator))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Productos Disponibles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Productos Disponibles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("id.Cliente:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nombres:");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Ap.Paterno:");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Ap.Materno:");

        txtSidcliente.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        txtSnombrecliente.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtSnombrecliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSnombreclienteActionPerformed(evt);
            }
        });

        txtSappaterno.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        txtSapmaterno.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSidcliente, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(txtSnombrecliente)
                    .addComponent(txtSappaterno)
                    .addComponent(txtSapmaterno))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSidcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSnombrecliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSappaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSapmaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Productos Disponibles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Id.Producto:");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Nombre:");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Precio:");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Stock:");

        txtSidproducto.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtSidproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSidproductoActionPerformed(evt);
            }
        });

        txtSnombreproducto.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        txtSprecioproducto.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        txtSstockproducto.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Productos Disponibles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Precio de Venta:");

        txtSprecioventa.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtSprecioventa.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        txtSprecioventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSprecioventaActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Cantidad de Venta:");

        txtcantidadventa.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtcantidadventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantidadventaActionPerformed(evt);
            }
        });

        btnagregarproducto.setBackground(new java.awt.Color(255, 255, 51));
        btnagregarproducto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnagregarproducto.setForeground(new java.awt.Color(0, 0, 0));
        btnagregarproducto.setText("Agregar Producto");
        btnagregarproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarproductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSprecioventa, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(txtcantidadventa, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnagregarproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtSprecioventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtcantidadventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnagregarproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSidproducto, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(txtSnombreproducto)
                    .addComponent(txtSprecioproducto)
                    .addComponent(txtSstockproducto))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtSidproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtSnombreproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtSprecioproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtSstockproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Productos Disponibles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Buscador:");

        txtbuscarproductos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtbuscarproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarproductosActionPerformed(evt);
            }
        });
        txtbuscarproductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarproductosKeyReleased(evt);
            }
        });

        tbproductos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tbproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbproductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbproductosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbproductos);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Click para  Seleccionar");

        btnMostrarProductosIterator.setBackground(new java.awt.Color(255, 255, 51));
        btnMostrarProductosIterator.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnMostrarProductosIterator.setForeground(new java.awt.Color(0, 0, 0));
        btnMostrarProductosIterator.setText("Mostrar productos");
        btnMostrarProductosIterator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarProductosIteratorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtbuscarproductos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMostrarProductosIterator)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtbuscarproductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrarProductosIterator)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Productos Disponibles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jPanel7.setForeground(new java.awt.Color(0, 0, 0));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Ultima Factura Creada:");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Seleccionar para Eliminar:");

        btneliminarresumenventa.setBackground(new java.awt.Color(255, 255, 51));
        btneliminarresumenventa.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btneliminarresumenventa.setForeground(new java.awt.Color(0, 0, 0));
        btneliminarresumenventa.setText("Eliminar");
        btneliminarresumenventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarresumenventaActionPerformed(evt);
            }
        });

        tbresumenventa.setBackground(new java.awt.Color(0, 102, 102));
        tbresumenventa.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tbresumenventa.setForeground(new java.awt.Color(0, 0, 0));
        tbresumenventa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idProducto", "N.Producto", "Precio Producto", "Cantidad Producto", "Sub Total"
            }
        ));
        jScrollPane3.setViewportView(tbresumenventa);

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("IVA (18%):");

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("TOTAL:");

        btncobrar.setBackground(new java.awt.Color(255, 255, 51));
        btncobrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btncobrar.setForeground(new java.awt.Color(0, 0, 0));
        btncobrar.setText("COBRAR");
        btncobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncobrarActionPerformed(evt);
            }
        });

        lbliva.setBackground(new java.awt.Color(255, 255, 255));
        lbliva.setText("----");

        lbltotal.setText("----");

        lblUltimaFactura.setText("----");
        lblUltimaFactura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cmbDescuento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Fijo", "Porcentaje" }));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Elegir tipo de descuento");

        btnAplicarDescuento.setBackground(new java.awt.Color(255, 255, 51));
        btnAplicarDescuento.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAplicarDescuento.setForeground(new java.awt.Color(0, 0, 0));
        btnAplicarDescuento.setText("Aplicar descuento");
        btnAplicarDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarDescuentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(lblUltimaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btneliminarresumenventa)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbliva, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAplicarDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btncobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUltimaFactura)
                            .addComponent(jLabel16)
                            .addComponent(btneliminarresumenventa)
                            .addComponent(jLabel15)
                            .addComponent(jLabel19)
                            .addComponent(cmbDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAplicarDescuento))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(lbliva, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(lbltotal))
                                .addGap(18, 18, 18)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnRestaurarFormulario.setBackground(new java.awt.Color(255, 255, 51));
        btnRestaurarFormulario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRestaurarFormulario.setForeground(new java.awt.Color(0, 0, 0));
        btnRestaurarFormulario.setText("RESTAURAR FORMULARIO");
        btnRestaurarFormulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarFormularioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRestaurarFormulario)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRestaurarFormulario)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private boolean validarAntesDeCobrar() {
        Responsabilidad.ValidadorCliente validadorCliente = new Responsabilidad.ValidadorCliente();
        Responsabilidad.ValidadorStock validadorStock = new Responsabilidad.ValidadorStock();
        validadorCliente.setSiguiente(validadorStock);

        if (txtSidcliente.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un cliente antes de cobrar.");
            return false;
        }

        if (tbresumenventa.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Debe agregar productos al resumen.");
            return false;
        }

        validadorCliente.manejar("validación");
        return true;
    }


    private void txtSnombreclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSnombreclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSnombreclienteActionPerformed

    private void txtSidproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSidproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSidproductoActionPerformed

    private void txtSprecioventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSprecioventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSprecioventaActionPerformed

    private void txtcantidadventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidadventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadventaActionPerformed

    private void btnagregarproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarproductoActionPerformed
        ControlAlquiler objetoVenta = new ControlAlquiler();
        objetoVenta.pasarproductosVentas(tbresumenventa, txtSidproducto, txtSnombreproducto,
                txtSprecioproducto, txtcantidadventa, txtSstockproducto);
        objetoVenta.calcularTotalPagar(tbresumenventa, lbliva, lbltotal);
    }//GEN-LAST:event_btnagregarproductoActionPerformed

    private void btneliminarresumenventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarresumenventaActionPerformed
        ControlAlquiler objetoVenta = new ControlAlquiler();
        objetoVenta.eliminarProductoSeleccionadoResumenVenta(tbresumenventa);
        objetoVenta.calcularTotalPagar(tbresumenventa, lbliva, lbltotal); //recañcular despues de eliminar
    }//GEN-LAST:event_btneliminarresumenventaActionPerformed

    //metodo de cobrar usando Facade + Command + Strategy + Builder
    
    private void btncobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncobrarActionPerformed
        if (!validarAntesDeCobrar()) return;

        FacadeAlquiler fachada = new FacadeAlquiler();
        fachada.realizarAlquiler(txtSidcliente, tbresumenventa);

        ComprobanteBuilder builder = new ComprobanteBuilder()
                .setCliente(txtSnombrecliente.getText())
                .setId(Integer.parseInt(txtSidcliente.getText()));

        double total = 0;
        for (int i = 0; i < tbresumenventa.getRowCount(); i++) {
            builder.addProducto(tbresumenventa.getValueAt(i, 1).toString());
            total += Double.parseDouble(tbresumenventa.getValueAt(i, 4).toString());
        }

        PatronesComportamiento.Strategy.ProcesadorDescuento procesador = new PatronesComportamiento.Strategy().new ProcesadorDescuento();
        String seleccion = cmbDescuento.getSelectedItem().toString();
        switch (seleccion) {
            case "Fijo":
                procesador.setEstrategia(new PatronesComportamiento.Strategy().new DescuentoFijo());
                break;
            case "Porcentaje":
                procesador.setEstrategia(new PatronesComportamiento.Strategy().new DescuentoPorcentaje());
                break;
            default:
                procesador.setEstrategia(t -> t);
        }

        double totalConDescuento = procesador.calcularTotalConDescuento(total);
        builder.setTotal(totalConDescuento);

        JOptionPane.showMessageDialog(null, builder.build().generarTexto());

        FormularioVenta formulario = new FormularioVenta();
        formulario.setEstado(
                txtSidcliente.getText() + ";" + txtSnombrecliente.getText(),
                txtSidproducto.getText() + ";" + txtSnombreproducto.getText()
        );
        mementoFormulario = formulario.guardarEstado();

        ControlAlquiler objetoVenta = new ControlAlquiler();
        objetoVenta.limpiarLuegoVenta(txtbuscarcliente, tbclientes, txtbuscarproductos, tbproductos,
                txtSidcliente, txtSnombrecliente, txtSappaterno, txtSapmaterno,
                txtSidproducto, txtSnombreproducto, txtSprecioproducto, txtSstockproducto,
                txtSprecioventa, txtcantidadventa, tbresumenventa, lbliva, lbltotal);

        objetoVenta.MostrarUltimaFactura(lblUltimaFactura);
    }//GEN-LAST:event_btncobrarActionPerformed

    private void txtbuscarclienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarclienteKeyReleased
        ControlAlquiler objetoVenta = new ControlAlquiler();
        objetoVenta.BuscarCliente(txtbuscarcliente, tbclientes);
    }//GEN-LAST:event_txtbuscarclienteKeyReleased

    private void txtbuscarclienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarclienteKeyTyped

    }//GEN-LAST:event_txtbuscarclienteKeyTyped

    private void tbclientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbclientesMouseClicked
        ControlAlquiler objetoVenta = new ControlAlquiler();
        objetoVenta.SeleccionarClienteAlquiler(tbclientes, txtSidcliente, txtSnombrecliente, txtSappaterno, txtSapmaterno);
    }//GEN-LAST:event_tbclientesMouseClicked

    private void txtbuscarproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarproductosActionPerformed

    }//GEN-LAST:event_txtbuscarproductosActionPerformed

    private void txtbuscarproductosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarproductosKeyReleased
        ControlAlquiler objetoVenta = new ControlAlquiler();
        objetoVenta.BuscarProducto(txtbuscarproductos, tbproductos);
    }//GEN-LAST:event_txtbuscarproductosKeyReleased

    private void tbproductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbproductosMouseClicked
        ControlAlquiler objetoVenta = new ControlAlquiler();
        objetoVenta.SeleccionarProductoAlquiler(tbproductos, txtSidproducto, txtSnombreproducto, txtSprecioproducto, txtSstockproducto, txtSprecioventa);
    }//GEN-LAST:event_tbproductosMouseClicked

    //metodo restaurar formulario usando memento
    
    private void btnRestaurarFormularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarFormularioActionPerformed
        if (mementoFormulario != null) {
            FormularioVenta formulario = new FormularioVenta();
            formulario.restaurarEstado(mementoFormulario);

            String[] datosCliente = mementoFormulario.getCliente().split(";");
            String[] datosProducto = mementoFormulario.getProducto().split(";");

            txtSidcliente.setText(datosCliente[0]);
            txtSnombrecliente.setText(datosCliente[1]);
            txtSidproducto.setText(datosProducto[0]);
            txtSnombreproducto.setText(datosProducto[1]);

            JOptionPane.showMessageDialog(null,
                    "Formulario restaurado.\nCliente: " + datosCliente[1] +
                    "\nProducto: " + datosProducto[1]);
        } else {
            JOptionPane.showMessageDialog(null, "No hay estado guardado para restaurar.");
        }
    }//GEN-LAST:event_btnRestaurarFormularioActionPerformed
    private void btnAplicarDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarDescuentoActionPerformed
        // TODO add your handling code here:
        double total = 0;
        for (int i = 0; i < tbresumenventa.getRowCount(); i++) {
            total += Double.parseDouble(tbresumenventa.getValueAt(i, 4).toString());
        }

        PatronesComportamiento.Strategy.ProcesadorDescuento procesador = new PatronesComportamiento.Strategy().new ProcesadorDescuento();
        String seleccion = cmbDescuento.getSelectedItem().toString();

        switch (seleccion) {
            case "Fijo":
                procesador.setEstrategia(new PatronesComportamiento.Strategy().new DescuentoFijo());
                break;
            case "Porcentaje":
                procesador.setEstrategia(new PatronesComportamiento.Strategy().new DescuentoPorcentaje());
                break;
            default:
                procesador.setEstrategia(t -> t); // Sin descuento
        }

        double totalConDescuento = procesador.calcularTotalConDescuento(total);
        JOptionPane.showMessageDialog(null,
                "Total antes del descuento: S/ " + total + "\n"
                + "Total con descuento aplicado: S/ " + totalConDescuento);
    }//GEN-LAST:event_btnAplicarDescuentoActionPerformed

    private void btnMostrarProductosIteratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarProductosIteratorActionPerformed
        // TODO add your handling code here:
        controlador.ControlAlquiler control = new controlador.ControlAlquiler();

        control.BuscarProducto(new JTextField(""), tbproductos);

        List<String> listaProductos = new ArrayList<>();
        for (int i = 0; i < tbproductos.getRowCount(); i++) {
            Object valor = tbproductos.getValueAt(i, 1); // columna "Nombre"
            if (valor != null) {
                listaProductos.add(valor.toString());
            }
        }

        // Usar Iterator
        PatronesComportamiento.Iterador iterador = new PatronesComportamiento.IteratorProductos(listaProductos);
        StringBuilder resumen = new StringBuilder("Productos disponibles:\n");
        while (iterador.tieneSiguiente()) {
            resumen.append("- ").append(iterador.siguiente()).append("\n");
        }

        //JOptionPane.showMessageDialog(null, resumen.toString());
    }//GEN-LAST:event_btnMostrarProductosIteratorActionPerformed

    private void btnMostrarClientesIteratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarClientesIteratorActionPerformed
        // TODO add your handling code here:
        controlador.ControlAlquiler control = new controlador.ControlAlquiler();

        control.BuscarCliente(new JTextField(""), tbclientes);

        List<String> listaClientes = new ArrayList<>();
        for (int i = 0; i < tbclientes.getRowCount(); i++) {
            Object valor = tbclientes.getValueAt(i, 1); // columna "Nombres"
            if (valor != null) {
                listaClientes.add(valor.toString());
            }
        }

        // Usar Iterator
        PatronesComportamiento.Iterador iterador = new PatronesComportamiento.IteratorProductos(listaClientes);
        StringBuilder resumen = new StringBuilder("Clientes registrados:\n");
        while (iterador.tieneSiguiente()) {
            resumen.append("- ").append(iterador.siguiente()).append("\n");
        }

        //JOptionPane.showMessageDialog(null, resumen.toString());
    }//GEN-LAST:event_btnMostrarClientesIteratorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicarDescuento;
    private javax.swing.JButton btnMostrarClientesIterator;
    private javax.swing.JButton btnMostrarProductosIterator;
    private javax.swing.JButton btnRestaurarFormulario;
    private javax.swing.JButton btnagregarproducto;
    private javax.swing.JButton btncobrar;
    private javax.swing.JButton btneliminarresumenventa;
    private javax.swing.JComboBox<String> cmbDescuento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblUltimaFactura;
    private javax.swing.JLabel lbliva;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JTable tbclientes;
    private javax.swing.JTable tbproductos;
    private javax.swing.JTable tbresumenventa;
    private javax.swing.JTextField txtSapmaterno;
    private javax.swing.JTextField txtSappaterno;
    private javax.swing.JTextField txtSidcliente;
    private javax.swing.JTextField txtSidproducto;
    private javax.swing.JTextField txtSnombrecliente;
    private javax.swing.JTextField txtSnombreproducto;
    private javax.swing.JTextField txtSprecioproducto;
    private javax.swing.JTextField txtSprecioventa;
    private javax.swing.JTextField txtSstockproducto;
    private javax.swing.JTextField txtbuscarcliente;
    private javax.swing.JTextField txtbuscarproductos;
    private javax.swing.JTextField txtcantidadventa;
    // End of variables declaration//GEN-END:variables
}
